Fixes #2022 Add common interface to indicate a building block contain…
Open-Systems-Pharmacology/OSPSuite.Core pull request #2027
Opened 2023-06-02 16:08 UTC by rwmcintosh

…s initial conditions

2023-06-04 21:26 UTC, msevestre requested changes
I do not like this change at all. I think adding the IBuidlignBlcok is one thing that we can agree upon, but removing the accessor to InitialCondition is going to be a harder sell for me and this was *not* what you explained. Each instance where it was removed results in code that is not idiomatic.
I am in favor of adding the InitialConditions accessor back, undoing all changes where it was removed in favor of some weird generics and go from there

2023-06-04 21:26 UTC, msevestre commented on src/OSPSuite.Core/Comparison/ExpressionProfileDiffBuilder.cs
> -         _enumerableComparer.CompareEnumerables(comparison, x => x.InitialConditions, x => x.Path);
I am not sure why this was removed? It makes sense for me to have a property InitialCoditions get at the ExpressionProfile level. Using the expression profile as an IEnumerable InitialCondition is not *intuitive*

2023-06-04 21:26 UTC, msevestre commented on src/OSPSuite.Core/Domain/Builder/ExpressionProfileBuildingBlock.cs
> +         sourceExpressionProfile.Each<InitialCondition>(initialCondition => Add(cloneManager.Clone(initialCondition)));
Same here. Each with an <> is very unexpected code. I think I want the old code back

2023-06-04 21:26 UTC, msevestre commented on src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
> +            .Concat(_simulationConfiguration.ExpressionProfiles.SelectMany<ExpressionProfileBuildingBlock, InitialCondition>(x => x)));
lol ok this is even more extreme. This code becomes unreadable

2023-06-04 21:26 UTC, msevestre commented on src/OSPSuite.Core/Serialization/Xml/BuildingBlockXmlSerializer.cs
> +         MapEnumerable<InitialCondition>(bb => bb, bb => bb.Add).WithMappingName(Constants.Serialization.INITIAL_CONDITIONS);
Please revert this also

2023-06-05 11:04 UTC, rwmcintosh commented
> I do not like this change at all. I think adding the IBuidlignBlock is one thing that we can agree upon, but removing the accessor to InitialCondition is going to be a harder sell for me and this was _not_ what you explained. Each instance where it was removed results in code that is not idiomatic. I am in favor of adding the InitialConditions accessor back, undoing all changes where it was removed in favor of some weird generics and go from there

Ok, that makes sense. That means that in places where you have the most derived version ```ExpressionProfileBuildingBlock``` you can use the accessor to get the initial conditions. You are not forced to get the enumerator of the building block, sometimes using weird generics.

2023-06-05 15:17 UTC, msevestre approved these changes

2023-06-05 15:17 UTC, merged