2374-v12-beta-events-top-container-is-not-generated-in-simulation
Open-Systems-Pharmacology/OSPSuite.Core pull request #2375
Opened 2024-12-09 12:14 UTC by benjaperez1983

Fixes #2374

# Description

"vents top container is not generated in simulation.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Integration tests
- [ ] Unit tests
- [ ] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

2024-12-10 10:51 UTC, rwmcintosh approved these changes

2024-12-12 02:14 UTC, msevestre requested changes

2024-12-12 02:14 UTC, msevestre commented on tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
> +         var organism = _simulationConfiguration.ModuleConfigurations[0].Module.BuildingBlocks.FirstOrDefault() as SpatialStructure;
this feels `very` weird to me
Why go to the list of building blocks, get the first one and assume it's spatial structure
we have sthg a bit better
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Module.cs#L58

2024-12-12 02:14 UTC, msevestre commented on tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
> +         organism.ShouldNotBeNull();
also this is not the organism. this is the spatial structure. IT's confusing becuase you have organism lie 349 and it's not even the same class

2024-12-12 13:47 UTC, msevestre approved these changes

2024-12-12 13:47 UTC, merged